### ISSUE TITLE
CSS模块化

### ISSUE THREAD

**Issue by liangwd** [liangwd/view#29]
### 局部命名
你可以用简短的描述性名字，而不需要关心命名冲突问题。
然后你要做的全部事情就是在 css/less 文件里写 .button {...}，并在组件里通过 styles.button 来引用他。

### 定义全局 CSS
CSS Modules 默认是局部作用域的，想要声明一个全局规则，可用 :global 语法。
```css
.title {
  color: red;
}
:global(.title) {
  color: green;
}
// 然后在引用的时候：
<App className={styles.title} /> // red
<App className="title" />        // green
```
