### ISSUE TITLE
css学习记录

### ISSUE THREAD

**Issue by liangwd** [liangwd/view#3]
ko
#### 页面渲染

页面渲染从上到下
css放在html标签的头部，页面从加载从上到下。先加载css再加载html,可以防止html加载处理未带样式，页面呈现不友好
js放在页面尾部：js执行功能，最后加载可以加快页面出现的速度，同时js是针对页面惊醒操作，必须保证页面节点都存在
#### 为什么要初始化css样式

因为浏览器的兼容性问题，不同浏览器对某些标签的默认值不同，如果不对浏览器进行初始化会出现浏览器直接出现页面显示差异。
初始化样式会对SEO有一定的影响，应该力求影响最小的情况下初始化。
#### 什么是css的sprite

CSS Sprites 其实就是把网页中一些背景图片整合到一张图片文件中，再利用 CSS 的"background-image"，"background-repeat"，"background-position" 的组合进行背景定位，background-position 可以用数字能精确的定位出背景图片的位置。这样可以减少很多图片请求的开销。
#### 选择器权重问题

内嵌>id>class>标签
#### 图片的设置位置

设置于css中：图片为固定的图片，不会因为操作人的不同或内容的不同而更换
设置于html中：图片与内容相关，会时时更新的则放在html的<img>标签中，由后台数据库调出
#### 文本和图像居中问题

文本水平居中：text-align:center;
文本垂直居中：fn1：设置line-height；fn2：设置padding相等
图像水平居中：margin：0 auto；
图像垂直居中：假设父级元素class为father

``` css
//fn1:
.father{ width:500px; height:300px; text-align:center; display: table-cell; vertical-align:middle;
//fn2:
.father{ width:500px;height:300px; text-align:center;}
.father:before{ content:""; display: inline-block;heigth:100%; vertical-align: middle;}
.father img{vertical-align: middle;}
```
#### display:none、visibility:hidden和overflow:hidden

display: none 对应元素不显示脱离文档流；
visibility：hidden 对应元素不显示但占用文档留，相当于opacity：0；
overflow：none 溢出隐藏
#### 定位机制

position：static 默认值。没有定位，元素出现在正常的文档流中(忽略top,bottom,left,right和z-index声明)
position：relative相对与自身的正常位置进行定位
position：absolute相对于static元素外的第一个父元素进行定位。以top,right,bottom,left进行定位
position：fixed绝对定位。相对于浏览器窗口进行定位。以top,righr,bottom,left进行定位
float：是元素浮动脱离文档流。若该元素的兄弟元素都是浮动元素，并且父元素没有设置宽高，则父元素的无法被撑开。要使父元素正常出现，需要为父元素设置宽高或者清除浮动。
#### 清除浮动的方法

fn1：在父元素的最后添加一个无意义的元素

``` css

.father:after{ content:""; display:block;clear:both;}

```

fn2：为父元素添加overflow：hidden

``` css

.father{overflow:hidden；_zoom:1；/*_zoom兼容IE6*/}

```
#### 滚动条出现页面不跳动

```
.wrap-outer {
    padding-left: calc(100vw - 100%);
}
```

tip：wrap-outer是父级元素
tip：calc是css3的属性计算，100vw整个页面的宽度(包含滚动条)，100%是可用页面的宽度，不包含滚动条
tip：以上支持IE9+

**Comment by liangwd** [comment]
#### 页面渲染
页面渲染从上到下
css放在html标签的头部，页面从加载从上到下。先加载css再加载html,可以防止html加载处理未带样式，页面呈现不友好
js放在页面尾部：js执行功能，最后加载可以加快页面出现的速度，同时js是针对页面惊醒操作，必须保证页面节点都存在

#### 为什么要初始化css样式
因为浏览器的兼容性问题，不同浏览器对某些标签的默认值不同，如果不对浏览器进行初始化会出现浏览器直接出现页面显示差异。
初始化样式会对SEO有一定的影响，应该力求影响最小的情况下初始化。

#### 什么是css的sprite
CSS Sprites 其实就是把网页中一些背景图片整合到一张图片文件中，再利用 CSS 的"background-image"，"background-repeat"，"background-position" 的组合进行背景定位，background-position 可以用数字能精确的定位出背景图片的位置。这样可以减少很多图片请求的开销。

#### 选择器权重问题
内嵌>id>class>标签

#### 图片的设置位置
设置于css中：图片为固定的图片，不会因为操作人的不同或内容的不同而更换
设置于html中：图片与内容相关，会时时更新的则放在html的<img>标签中，由后台数据库调出

#### 文本和图像居中问题
文本水平居中：text-align:center;
文本垂直居中：fn1：设置line-height；fn2：设置padding相等
图像水平居中：margin：0 auto；
图像垂直居中：假设父级元素class为father

```css
//fn1:
.father{ width:500px; height:300px; text-align:center; display: table-cell; vertical-align:middle;
//fn2:
.father{ width:500px;height:300px; text-align:center;}
.father:before{ content:""; display: inline-block;heigth:100%; vertical-align: middle;}
.father img{vertical-align: middle;}
```

#### display:none、visibility:hidden和overflow:hidden
display: none 对应元素不显示脱离文档流；
visibility：hidden 对应元素不显示但占用文档留，相当于opacity：0；
overflow：none 溢出隐藏

#### 定位机制
position：static 默认值。没有定位，元素出现在正常的文档流中(忽略top,bottom,left,right和z-index声明)
position：relative相对与自身的正常位置进行定位
position：absolute相对于static元素外的第一个父元素进行定位。以top,right,bottom,left进行定位
position：fixed绝对定位。相对于浏览器窗口进行定位。以top,righr,bottom,left进行定位
float：是元素浮动脱离文档流。若该元素的兄弟元素都是浮动元素，并且父元素没有设置宽高，则父元素的无法被撑开。要使父元素正常出现，需要为父元素设置宽高或者清除浮动。

#### 清除浮动的方法
fn1：在父元素的最后添加一个无意义的元素
```css

.father:after{ content:""; display:block;clear:both;}

```
fn2：为父元素添加overflow：hidden
```css

.father{overflow:hidden；_zoom:1；/*_zoom兼容IE6*/}

```
